/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationBody: typeof import('./src/components/Application/ApplicationBody.vue')['default']
    ApplicationRoot: typeof import('./src/components/Application/ApplicationRoot.vue')['default']
    ApplicationTransition: typeof import('./src/components/Application/ApplicationTransition.vue')['default']
    BaseLayout: typeof import('./src/layout/BaseLayout.vue')['default']
    CommonCom: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/CommonCom.vue')['default']
    copy: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/X01_ZCL_WRTIE_ATTR_REQ copy.vue')['default']
    EByteZigbeeBuildIndex: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/EByteZigbeeBuildIndex.vue')['default']
    HomeLayout: typeof import('./src/layout/HomeLayout.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PageView: typeof import('./src/components/PageView.vue')['default']
    PwaUpdateNotification: typeof import('./src/components/Pwa/PwaUpdateNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/Site/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/Site/SiteHeader.vue')['default']
    TextRadixCard: typeof import('./src/components/Tools/Text/TextRadixCard.vue')['default']
    X01_ZCL_WRTIE_ATTR_REQ: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/X01_ZCL_WRTIE_ATTR_REQ.vue')['default']
    X01_ZclWrtieAttrReq: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/X01_ZclWrtieAttrReq.vue')['default']
    X02_ZclSendIndex: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/X02_ZclSendIndex.vue')['default']
    X0F_ZCL_CMD_SEND: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/X0F_ZCL_CMD_SEND.vue')['default']
    ZCL_CommonCom: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/ZCL_CommonCom.vue')['default']
    ZclWrtieAttrReq: typeof import('./src/components/Tools/Hardware/EByte/Zigbee/build/2_TYPE_ZCL_SEND/ZclWrtieAttrReq.vue')['default']
  }
}
